---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: llmwarden-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    # For local development, use URL instead of service
    url: https://host.docker.internal:9443/mutate-llmwarden-llmwarden-io-v1alpha1-llmaccess
    caBundle: # Will be injected by cert-manager
  failurePolicy: Fail
  name: mllmaccess-v1alpha1.kb.io
  rules:
  - apiGroups:
    - llmwarden.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - llmaccesses
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    url: https://host.docker.internal:9443/mutate-v1-pod
    caBundle: # Will be injected by cert-manager
  failurePolicy: Ignore
  name: mpod.llmwarden.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: llmwarden-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    url: https://host.docker.internal:9443/validate-llmwarden-llmwarden-io-v1alpha1-llmaccess
    caBundle: # Will be injected by cert-manager
  failurePolicy: Fail
  name: vllmaccess-v1alpha1.kb.io
  rules:
  - apiGroups:
    - llmwarden.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - llmaccesses
  sideEffects: None
