apiVersion: llmwarden.llmwarden.io/v1alpha1
kind: LLMAccess
metadata:
  labels:
    app.kubernetes.io/name: llmwarden
    app.kubernetes.io/managed-by: kustomize
  name: llmaccess-sample
spec:
  # TODO(user): Add fields here
