apiVersion: llmwarden.io/v1alpha1
kind: LLMProvider
metadata:
  labels:
    app.kubernetes.io/name: llmwarden
    app.kubernetes.io/managed-by: kustomize
  name: llmprovider-sample
spec:
  # TODO(user): Add fields here
