{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "llmwarden.fullname" . }}-leader-election
  namespace: {{ include "llmwarden.leaderElectionNamespace" . }}
  labels:
    {{- include "llmwarden.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "llmwarden.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "llmwarden.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
