{{- if .Values.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llmwarden.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llmwarden.labels" . | nindent 4 }}
  {{- with .Values.webhook.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
  - name: https
    port: {{ .Values.webhook.service.port }}
    targetPort: webhook
    protocol: TCP
  selector:
    {{- include "llmwarden.selectorLabels" . | nindent 4 }}
{{- end }}
